apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: r_map
  tags:
    - public
spec:
  type: website
  lifecycle: production
  owner: group:default/geonorge
  system: system:default/geonorge
