// The action types

export const UPDATE_SEARCH_STRING = 'UPDATE_SEARCH_STRING'
export const UPDATE_SEARCH_STRING_FROM_URL = 'UPDATE_SEARCH_STRING_FROM_URL'

export const SEARCH_QUERY = "SEARCH_QUERY"
export const SEARCH_LIST = "SEARCH_LIST"
